baseURL = "http://gnome.or.kr"
languageCode = "en-us"
title = "GNOME KOREA"
theme = "book"
sectionPagesMenu = "main"

[params]
  author = "GNOME KOREA"
  share = true
  BookLogo = 'gnome-kr.png'
  BookMenuBundle = '/menu'
  Copyright = "2020 GNOME KOREA"

